### PR TITLE
Comments on blogpost-1

### PR DESCRIPTION
**Pull request by mathijshenquet**

### CODE REVIEW

**Comment by mathijshenquet** [comment]
I think its better to use : instead of \mid in set notation when you are using ||x|| or |x| for norms.

**Comment by mathijshenquet** [comment]
Often there was a enumeration where I felt it would be better to use subheadings (`#, ##, ###, ####` in markdown) for clearity.

**Comment by mathijshenquet** [comment]
What is \cal{O} supposed to mean in the motivating example 2?

**Comment by mathijshenquet** [comment]
I feel like you should say somewhere what formal geometry is supposed to be, probably best between the heading
"A map of formal geometry" and the caviats in the next paragraph. I guess this would be to find a category of spaces with some extra local structure which would be the codomain of the functor S?

**Review by LouisYRYJ — COMMENTED** [review]
Test

**Review by LouisYRYJ — APPROVED** [review]
Structuring much better now, thanks
Also reformulated some things in response to your comments

**Pull request merged**
